"use client"

import { useQuery } from "@tanstack/react-query"
import { api } from "@/lib/api/client"
import { ShapWaterfall } from "@/components/cases/ShapWaterfall"
import { CopilotChat } from "@/components/cases/CopilotChat"
import { OpaquePanel } from "@/components/shared/OpaquePanel"
import { Button } from "@/components/ui/button"
import { useRole } from "@/store"
import { Check, X } from "lucide-react"

export default function CaseDetailPage({ params }: { params: { caseId: string } }) {
  const role = useRole()
  
  // Mock data for case
  const { data: caseDetail, isLoading } = useQuery({
    queryKey: ['case', params.caseId],
    queryFn: () => Promise.resolve({
      id: params.caseId,
      prediction_log_id: "log-1",
      status: "OPEN",
      priority: "HIGH",
      assigned_to: "Unassigned",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      prediction: {
        id: "log-1",
        transaction_id: "txn-992384",
        amount: 2450.00,
        risk_level: "high" as any,
        status: "PENDING_REVIEW" as any,
        timestamp: new Date().toISOString(),
        fraud_probability: 0.92,
        features: {
          "velocity_10m": 5.4,
          "amount_std_dev": 2.1,
          "ip_risk": 1.8,
          "device_new": 0.5,
          "distance_km": -0.2
        }
      }
    }),
  })

  if (isLoading || !caseDetail) return <div className="animate-pulse h-full bg-mist/5 rounded-xl" />

  const canApproveOverride = role === "Senior Analyst" || role === "Admin/Executive"

  return (
    <div className="space-y-6 h-full flex flex-col">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="font-display text-xl font-medium text-mist">
            Case <span className="font-mono text-signal">{caseDetail.id}</span>
          </h2>
          <p className="text-sm font-sans text-mist/60 mt-1">
            Transaction: <span className="font-mono">{caseDetail.prediction?.transaction_id}</span> • 
            Priority: <span className="text-ember font-medium">{caseDetail.priority}</span>
          </p>
        </div>
        
        <div className="flex gap-3">
          {canApproveOverride ? (
            <>
              <Button className="bg-signal text-[var(--text-on-signal)] hover:bg-signal/80 font-display">
                <Check className="w-4 h-4 mr-2" /> Approve (Fraud)
              </Button>
              <Button className="bg-trench border border-mist/20 text-mist hover:bg-mist/10 font-display">
                <X className="w-4 h-4 mr-2" /> Override (Safe)
              </Button>
            </>
          ) : (
            <Button className="bg-trench border border-mist/20 text-mist hover:bg-mist/10 font-display">
              Update Status
            </Button>
          )}
        </div>
      </div>

      {/* Two Column Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 flex-1 min-h-0">
        
        {/* Left Column: Details & SHAP */}
        <div className="lg:col-span-2 space-y-6 flex flex-col">
          <OpaquePanel className="p-6">
            <h3 className="font-display text-lg text-mist mb-4">Transaction Details</h3>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-xs font-sans text-mist/60 uppercase">Amount</p>
                <p className="font-mono text-mist text-lg">${caseDetail.prediction?.amount.toFixed(2)}</p>
              </div>
              <div>
                <p className="text-xs font-sans text-mist/60 uppercase">Fraud Probability</p>
                <p className="font-mono text-ember text-lg">{(caseDetail.prediction?.fraud_probability || 0) * 100}%</p>
              </div>
              {/* More mock details... */}
            </div>
          </OpaquePanel>

          <ShapWaterfall features={caseDetail.prediction?.features} />
        </div>

        {/* Right Column: Copilot & Audit Trail */}
        <div className="lg:col-span-1 flex flex-col gap-6 h-full">
          <div className="flex-1 min-h-[300px]">
            <CopilotChat caseId={caseDetail.id} />
          </div>
          
          <OpaquePanel className="h-[200px] overflow-y-auto p-4">
            <h3 className="font-display text-sm text-mist mb-3">Audit Trail</h3>
            <div className="space-y-3">
              <div className="text-sm">
                <span className="font-mono text-[10px] text-mist/50 block">10:45:12 AM</span>
                <span className="font-sans text-mist/80">Alert generated by Model V2</span>
              </div>
              <div className="text-sm">
                <span className="font-mono text-[10px] text-mist/50 block">10:46:01 AM</span>
                <span className="font-sans text-mist/80">Case created automatically</span>
              </div>
            </div>
          </OpaquePanel>
        </div>
      </div>
    </div>
  )
}
