"""Initial postgres schema

Revision ID: fe89aee7afdd
Revises: 
Create Date: 2026-07-07 15:25:35.743158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models


# revision identifiers, used by Alembic.
revision: str = 'fe89aee7afdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('cases_resolved', sa.Integer(), nullable=False),
    sa.Column('avg_resolution_mins', sa.Float(), nullable=False),
    sa.Column('false_positive_count', sa.Integer(), nullable=False),
    sa.Column('true_positive_count', sa.Integer(), nullable=False),
    sa.Column('cases_escalated', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('old_value_json', src.models.FlexibleJSON(), nullable=True),
    sa.Column('new_value_json', src.models.FlexibleJSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('condition_json', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('risk_level_bump', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('copilot_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('prediction_log_id', sa.Integer(), nullable=True),
    sa.Column('query_context_json', src.models.FlexibleJSON(), nullable=False),
    sa.Column('llm_response', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('is_cached', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('fraud_count', sa.Integer(), nullable=False),
    sa.Column('avg_amount', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=False),
    sa.Column('risk_score_avg', sa.Float(), nullable=False),
    sa.Column('last_transaction_at', sa.String(), nullable=True),
    sa.Column('first_transaction_at', sa.String(), nullable=True),
    sa.Column('risk_trend', sa.String(), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('country_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('drift_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('psi_score', sa.Float(), nullable=False),
    sa.Column('alert_triggered', sa.Boolean(), nullable=False),
    sa.Column('baseline_mean', sa.Float(), nullable=True),
    sa.Column('current_mean', sa.Float(), nullable=True),
    sa.Column('baseline_std', sa.Float(), nullable=True),
    sa.Column('current_std', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('pkl_path', sa.String(), nullable=False),
    sa.Column('roc_auc', sa.Float(), nullable=True),
    sa.Column('pr_auc', sa.Float(), nullable=True),
    sa.Column('precision_val', sa.Float(), nullable=True),
    sa.Column('recall_val', sa.Float(), nullable=True),
    sa.Column('f1_val', sa.Float(), nullable=True),
    sa.Column('n_estimators', sa.Integer(), nullable=True),
    sa.Column('training_date', sa.String(), nullable=False),
    sa.Column('dataset_size', sa.Integer(), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('prediction_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('transaction_json', src.models.FlexibleJSON(), nullable=False),
    sa.Column('ml_probability', sa.Float(), nullable=False),
    sa.Column('ml_risk_level', sa.String(), nullable=False),
    sa.Column('ml_risk_score', sa.Integer(), nullable=False),
    sa.Column('final_risk_level', sa.String(), nullable=False),
    sa.Column('final_risk_score', sa.Integer(), nullable=False),
    sa.Column('policy_override_applied', sa.Boolean(), nullable=False),
    sa.Column('policy_reasons_json', src.models.FlexibleJSON(), nullable=False),
    sa.Column('suspicious_signal_count', sa.Integer(), nullable=True),
    sa.Column('alert_json', src.models.FlexibleJSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('last_login', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('fraud_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('prediction_log_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('evidence_json', src.models.FlexibleJSON(), nullable=True),
    sa.Column('notes_json', src.models.FlexibleJSON(), nullable=True),
    sa.Column('timeline_json', src.models.FlexibleJSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_log_id'], ['prediction_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fraud_cases')
    op.drop_table('users')
    op.drop_table('prediction_logs')
    op.drop_table('model_registry')
    op.drop_table('drift_snapshots')
    op.drop_table('customer_profiles')
    op.drop_table('copilot_logs')
    op.drop_table('business_rules')
    op.drop_table('audit_logs')
    op.drop_table('analyst_metrics')
    # ### end Alembic commands ###
